// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewkmmumyktsmbegytblv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3a21tdW15a3RzbWJlZ3l0Ymx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyODMyMTIsImV4cCI6MjA1OTg1OTIxMn0.SkG00sQAQ1f5sJfFD5V9Ay1PcWMPCv_AH67M9I-V_q4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);